### ISSUE TITLE
Cannot disable Auto Discover

### ISSUE THREAD

**Issue by robgarrett** [jimboca/udi-harmony-poly#20]
I must confess that I'm new to Polyglot and Harmony. I'd like to stop all my devices showing up in my ISY and instead just show certain activities. I deleted the nodes I didn't want and then tried to set "Auto Discover" to false in ISY, but it resets back to true (immediately).

I'm not sure how drivers work, but looking at the code I see GV8 is the auto discover setting.

Also, I get a lot of request failed errors in ISY when I add a hub to a scene.

Help much appreciated.

**Comment by jimboca** [comment]
Sorry, I've been traveling. I'll take a look when I get time for the auto discover issue. I don't understand why you would add the hub to a scene? You should be able to add devices or activities.

**Comment by robgarrett** [comment]
I actually figured it out. It's turned off SSL in polyglot, butt my ISY still had it enabled.

Thanks

R

rob@robgarrett.com
@rgarrettpro


________________________________

**Comment by jimboca** [comment]
Ok, but you shouldn't need to turn off SSLl on the ISY.

**Comment by robgarrett** [comment]
Right, I only turned it off on polyglot b/c I was fed up with the warning in the browser. This didn't jive well with ISY, which assumes SSL is enabled on polyglot. So, I turned it back on.

R

rob@robgarrett.com
@rgarrettpro


________________________________
