### ISSUE TITLE
Connecting Harmony Companion Remote buttons with ISY Insteon devices

### ISSUE THREAD

**Issue by ChrisChiera** [jimboca/udi-harmony-poly#29]
I have many insteon devices that I have setup with ISY and have an ISY homekit homebridge plugin to expose them all to homekit successfully.  I also have Harmony Hubs with the newer companion remote. Those remotes include 2 light switch buttons and 2 outlet switch buttons and dimmer toggle. I'd like to have those control certain insteon lights. While the Insteon Hub natively integrates with Insteon that hub is a dud, so trying to find a solution with ISY. May be a dumb question but is that what this plugin does? Connects ISY and Harmony, so that when I'm in the Harmony app and setting up the remote buttons and search for IP devices it will detect the Isy hub and allow me to assign buttons to certain lights/outlets and allow the dimmer toggle to work? Or is this plugin meant for something else?

**Comment by jimboca** [comment]
Yes basically that's what it does. It makes devices on the ISY look like a Hue hub which the Harmony can control.

**Comment by sjmorrow** [comment]
For those finding this issue in the future, this is actually not the NodeServer you are looking for. If you are looking to have your insteon devices show up in Harmony, you need to use the following NodeServer: https://github.com/jimboca/udi-poly-hue-emu
